### ISSUE TITLE
Getting "Killed" error when run on kp20k Dataset

### ISSUE THREAD

**Issue by nanthamanish** [xgeric/UCPhrase-exp#4]
![UCPhrase-error (2)](https://user-images.githubusercontent.com/59362872/123514167-1c754380-d6af-11eb-8ec1-423acb7b36c7.png)

When I run ```python exp.py --gpu 0 --dir_data ../data/kp20k```, I get the Killed error.
While debugging I found the error happens at the ```return torch.tensor(padded_tensor, dtype=torch.float32)``` (line 66 of ```src/model_att/model.py```)

Is there a way to fix this?

**Comment by xgeric** [comment]
Hi, looks like a resource issue, if the job was not manually terminated by a server admin. Could you please check the memory usage and the swap space? If it was due to the lack of resource, you can try to reduce the batch size at [this line](https://github.com/xgeric/UCPhrase-exp/blob/master/src/model_att/trainer.py#L20). Please have a try and let us know if the issue still exists. Thanks!

**Comment by nanthamanish** [comment]
Hi! 
I did try reducing the batch size (from 2048 till 4), but I got the same error again. On kp20k, the numpy array has the dimensions of (6529257, 36, 10, 10) resulting in a total size of 23505325200. And the process gets killed when converting this to a torch tensor. Let me know if there is an optimization possible to run it on my system. Thanks :)

**Comment by xgeric** [comment]
Thank you for the feedback! Sorry it was not the batch size that matters, since at this step we were loading all training instances to memory, so it may exceed memory limit. To verify this, you check the memory usage, or try to add `instances = instances[:100]` to see if the error goes away. It would help if you can test it on a machine with larger memory for now.
